import { Hono } from 'hono';
import { serve } from '@hono/node-server';

const app = new Hono();

// Helper function to escape HTML to prevent XSS
const escapeHtml = (unsafe) => {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
};

// Helper function to generate HTML page
const generateHtmlPage = (title, content) => {
  const escapedTitle = escapeHtml(title);
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapedTitle}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
        }
        p {
            color: #666;
            line-height: 1.6;
        }
        a {
            color: #0066cc;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .nav {
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <div class="container">
        ${content}
    </div>
</body>
</html>`;
};

// Root route
app.get('/', (c) => {
  const content = `
    <h1>Welcome to Vrchni</h1>
    <p>This is a single Hono.js server that serves HTML on each route.</p>
    <div class="nav">
      <h3>Try these routes:</h3>
      <ul>
        <li><a href="/route/home">Home Route</a></li>
        <li><a href="/route/about">About Route</a></li>
        <li><a href="/route/contact">Contact Route</a></li>
        <li><a href="/route/anything">Any Route You Want</a></li>
      </ul>
    </div>
  `;
  return c.html(generateHtmlPage('Vrchni - Home', content));
});

// Wildcard route handler for /route/*
app.get('/route/*', (c) => {
  const path = c.req.path;
  // More robust route name extraction
  const routeName = path.startsWith('/route/') 
    ? path.substring('/route/'.length).trim() || 'unknown'
    : 'unknown';
  const escapedRouteName = escapeHtml(routeName);
  
  const content = `
    <h1>Route: ${escapedRouteName}</h1>
    <p>You are currently viewing the <strong>${escapedRouteName}</strong> route.</p>
    <p>This page was dynamically generated by the Hono.js server.</p>
    <div class="nav">
      <p><a href="/">← Back to Home</a></p>
      <h3>Try other routes:</h3>
      <ul>
        <li><a href="/route/home">Home</a></li>
        <li><a href="/route/about">About</a></li>
        <li><a href="/route/contact">Contact</a></li>
        <li><a href="/route/dashboard">Dashboard</a></li>
        <li><a href="/route/settings">Settings</a></li>
      </ul>
    </div>
  `;
  
  return c.html(generateHtmlPage(`Vrchni - ${escapedRouteName}`, content));
});

// 404 handler
app.notFound((c) => {
  const content = `
    <h1>404 - Not Found</h1>
    <p>The page you're looking for doesn't exist.</p>
    <p>Try visiting a route like <a href="/route/example">/route/example</a></p>
    <div class="nav">
      <p><a href="/">← Back to Home</a></p>
    </div>
  `;
  return c.html(generateHtmlPage('404 - Not Found', content), 404);
});

const port = process.env.PORT || 3000;

console.log(`Server is running on http://localhost:${port}`);

serve({
  fetch: app.fetch,
  port
});
